### ISSUE TITLE
Export Content Type Form Is Missing

### ISSUE THREAD

**Issue by golanorbi** [d6lts/cck#5]
Hi,

For some reason, the by reference "&" was omitted from the argument `$vars` in the function `template_preprocess_content_copy_export_form($vars)` in `modules\cck\modules\content_copy\content_copy.module`

So instead of `template_preprocess_content_copy_export_form(&$vars)` this release has `template_preprocess_content_copy_export_form($vars)`

Consequently, the path `admin/content/types/export` won't show the content types list for exporting.

**Comment by rmuit** [comment]
Just dropping a reference: https://www.drupal.org/project/cck/issues/2230081

**Comment by dsnopek** [comment]
Thanks! I just committed a fix to this in https://github.com/d6lts/cck/commit/548ff853ec53c134dac3c5821cf8bd109fa553aa
